### ISSUE TITLE
Inkonsistenz zwischen Dokument und Schema für Parameter "presystem"/"systemType" (Prio: High)

### ISSUE THREAD

**Issue by meppingvector** [VDVde/VDV463#1]
Im Dokument wird der Parameter als "systemType" beschrieben, im Schema als presystem. Da manche Hersteller das Dokument als Vorlage nehmen und andere das Schema, könnte eine inkompatible Kommunikation entstehen.
 
Änderungsvorschlag:
- Parameter im Dokument zu "presystem" umbenennen
- Hinweis im Dokument ergänzen, dass im Zweifel das Schema richtig ist. Es wird allen Herstellern empfohlen, den Programmcode aus den Schema Dateien zu generieren, um Tippfehler o.ä. zu vermeiden.

**Comment by maikwoehl-psi** [comment]
Das halte ich für eine sinnvolle Änderung.

**Comment by maikwoehl-psi** [comment]
Die Umbenennung wird in der nächsten Aktualisierung der VDV463-Schrift erfolgen.

**Comment by roastedmonk** [comment]
@maikwoehl-psi @mafrenzelpsi 
What should be followed "presystem" or "systemType" ?

**Comment by maikwoehl-psi** [comment]
> @maikwoehl-psi @mafrenzelpsi What should be followed "presystem" or "systemType" ?

Hi @roastedmonk,

the references of `systemType` in the official specification available at https://knowhow.vdv.de/documents/463/ will be changed to `presystem`. The schema will not change in that regard.

Best regards,
Maik Wöhl
