### ISSUE TITLE
Was passiert mit der "ChargingPrediction", wenn die Batterie voll ist?

### ISSUE THREAD

**Issue by maikwoehl-psi** [VDVde/VDV463#13]
Ein Kollege hat sich gefragt was mit der _ChargingPrediction_ passiert, wenn die Batterie voll ist?

Die Spezifikation suggeriert in den Beispielen, dass die Einträge dann beim letzten Wert stehen bleiben. 
Mathematisch korrekt wäre für ihn jedoch das Ansteigen der Vorhersage ins Unendliche.

**Comment by gthiesing** [comment]
Die Schrift sagt:
Der Typ ChargingPredictionDataFinalSoc hat folgende Attribute:
•predictedFinalSoc: Prognose, welcher SoC in %, der zur zeitlichen Zielvorgabe erreicht
sein wird
•predictedTime: Prognose, bis wann der PredictedFinalSoc erreicht sein wird

m.E. kann eine Lösung sein: predictedFinalSoC = 100% mit predictedTime: _der aktuelle Zeitpunkt_

**Comment by maikwoehl-psi** [comment]
Wenn ich die Entwürfe korrekt interpretiere, wird das Thema indirekt in der Konfliktbehandlung mit aufgegriffen. Also vermutlich haben wir dann bei Beschluss der daraus resultierenden Änderungen eine spezifizierte Antwort dazu.

**Comment by maikwoehl-psi** [comment]
Im Rahmen der Diskussion zur Konfliktbehandlung gelöst.
