### ISSUE TITLE
Unschärfe in der Benutzung des Begriffes „voltage“

### ISSUE THREAD

**Issue by DohmenClaus** [VDVde/VDV463#18]
Es gibt eine Unschärfe in der Benutzung des Begriffes „voltage“: 
Manche Ladesystemhersteller liefern einen in OCPP definierten Wert, der die Eingangsspannung des Ladegerätes wiedergibt. Dieser Wert ist im Kontext der VDV463 irrelevant, hier interessieren nur Ladespannungen am Ausgang des Ladegerätes. 
Beschluss Arbeitsgruppensitzung 4.7.2023: in VDV463 klarer beschreiben

**Comment by maikwoehl-psi** [comment]
- [x] Spezifikationsdokument überarbeiten

**Comment by maikwoehl-psi** [comment]
![grafik](https://github.com/VDVde/VDV463/assets/89198198/c9eb1a8f-12a4-40aa-bfb5-f912ae5ff3d3)
