### ISSUE TITLE
Version number of referenced documents

### ISSUE THREAD

**Issue by gthiesing** [VDVde/VDV463#19]
The version no. of the referenced documents, i.e. VDV 261 and OCPP should be added in teh foreword or introduction for information purposes.
All attributes enum values etc. should be incorporated in the vdv 463 directly corresponding to the referenced document to avoid the necessity of reading additonal documents in parallel.

Referenced attributes or enums should be marked by a note, e.g. refer to VDV 261.

- [x] Herr Wöhl überarbeitet Dokument entsprechend Beschlüssen vom 11.4.2024

**Comment by maikwoehl-psi** [comment]
- [ ] Spezifikationsänderungen

**Comment by maikwoehl-psi** [comment]
![grafik](https://github.com/VDVde/VDV463/assets/89198198/6a9b780b-3d01-43ca-9a36-ed641ff5106f)
![grafik](https://github.com/VDVde/VDV463/assets/89198198/c3826804-8d6f-48ac-ab81-101b825d80af)
![grafik](https://github.com/VDVde/VDV463/assets/89198198/93a785c9-5233-4621-9e39-23f1a8df812e)
![grafik](https://github.com/VDVde/VDV463/assets/89198198/ce9b5963-2f29-4b83-a1e8-b0eacd37aae5)

**Comment by DohmenClaus** [comment]
Beschlüsse der Arbeitsgruppe am 11.4.2024 zum Umgang mit Referenzen auf externe Dokumente:

1) Das VDV463-Dokument soll "self-contained" sein, d.h. inbesondere dass benutzte enum-Werte (z.B. aus VDV261) im Dokument aufgelistet und nicht nur referenziert werden.
2) Im Kapitel "Regelwerke – Normen und Empfehlungen" sollen die Normen _mit Version_ aufgeführt werden, also z.B. VDV261 _05/2023 Edition2_
3) Beim Bezug auf Quell-Normen soll im Text immer auch der Querverweis auf den entsprechenden Eintrag im Kapitel "Regelwerke – Normen und Empfehlungen"  eingefügt sein, also z.B. "VDV261 **(4)**"

**Comment by DohmenClaus** [comment]
Herr Wöhl überarbeitet Dokument entsprechend

**Comment by maikwoehl-psi** [comment]
- [x] Im Kapitel "Regelwerke – Normen und Empfehlungen" sollen die Normen mit Version aufgeführt werden, also z.B. VDV261 05/2023 Edition2
- [x] Beim Bezug auf Quell-Normen soll im Text immer auch der Querverweis auf den entsprechenden Eintrag im Kapitel "Regelwerke – Normen und Empfehlungen" eingefügt sein, also z.B. "VDV261 (4)"

In der Online-Version kann ich leider keine Querverweise nutzen. Ich kann das Dokument leider auch nicht lokal in Word öffnen. Dazu müsste ich es vorher einmal herunterladen und dann aktualisiert wieder hochladen. Das werde ich tun, denke ich.

Für Aufgabe 1 benötige ich noch mehr Zeit.

**Comment by maikwoehl-psi** [comment]
- [x] Das VDV463-Dokument soll "self-contained" sein, d.h. inbesondere dass benutzte enum-Werte (z.B. aus VDV261) im Dokument aufgelistet und nicht nur referenziert werden.

Diese Anpassung ist nun auch vorgenommen und im Dokument mit dem Titel "VDV-463-V1.1.0_mw.docx" auf dem Sharepoint abgelegt.

Die Querverweise zu den Normen sind nun korrekt als Word-Querverweis eingestellt.
