### ISSUE TITLE
ChargingPredictionData Verbesserung

### ISSUE THREAD

**Issue by BenjaminKowatschVector** [VDVde/VDV463#22]
Im Rahmen der Arbeitsgruppe zur Konfliktbehandlung wurde der Bedarf eines weiteren Tupels "ChargingPredictionDataDepartureTime" innerhalb der Struktur "ChargingPredictionData" festgestellt, um die Prognose des LMS zum Zeitpunkt der geplanten Abfahrtszeit an das Vorsystem zu übermitteln.
Zudem war zuvor das Feld "chargingPredictionDataMinSoc" in der Struktur "ChargingPredictionData" ein Pflichtfeld.
Nach dem Beschluss der letzten Gremiumssitzung werden alle Felder in der Struktur "ChargingPredictionData" als technisch optional definiert.

**Comment by DohmenClaus** [comment]
Spezifikation und Schema sind angepasst
