### ISSUE TITLE
Fahrzeugidentifizierung

### ISSUE THREAD

**Issue by Sarlan-PSI** [VDVde/VDV463#30]
[CR 2024 VDV463_V1.1 - 2.docx](https://github.com/VDVde/VDV463/files/14667410/CR.2024.VDV463_V1.1.-.2.docx)

- [x] @BenjaminKowatschVector passt Abbildung kap. 2.3.5 an

**Comment by DohmenClaus** [comment]
Spezifikation angepasst in Kap. 2.3.5.

**Comment by BenjaminKowatschVector** [comment]
Spezifikationsanpassung ist erfolgt.
