### ISSUE TITLE
Element „AutomaticPreconditioningType“ unvollständig 

### ISSUE THREAD

**Issue by TNeuHochbahn** [VDVde/VDV463#5]
Aus unserer Sicht fehlt im Element „AutomaticPreconditioningType“ analog zum beschriebenen Element "ManualPreconditioningType" das Feld welches den Startzeitpunkt der Vorkonditionierung "SystemPreconditioningStartTime" übermittelt. Ohne einen Startzeitpunkt kann das LMS nicht die benötigte Leistung rechtzeitig vor dem Abfahrtszeitpunkt/ dem Beginn der Vorkonditionierung bereitstellen.

Vorschlag: Entsprechende Felder im "AuotmaticPreconditionType" ergänzen.

**Comment by hojatzarif** [comment]
Die automatische Vorkonditionierung wird über die VDV261 Kommunikation zwischen Bus und LMS umgesetzt. Dabei gibt der Bus den Startzeitpunkt der Vorkonditionierung vor. Vom Vorsystem über das LMS wird nur der Wunsch nach einer Vorkonditionierung, die Art der Vorkonditionierung und die Endzeitpunkt der Vorkonditionierung übermittelt. Den Beginn der Vorkonditionierung bestimmt der Bus selbstständig.

**Comment by mafrenzelpsi** [comment]
Eine SystemPreconditioningStartTime, wie von @TNeuHochbahn vorgeschlagen, wird m.E. dann erforderlich, wenn die Ladeleistung nach Erreichung eines Zielladezustandes auf eine minimale Erhaltungsladung reduziert wurde und für die PreKonditionierung wieder erhöht werden muß. Alternativ könne man auf den Gedanken kommen die von Fahrzeug berechnete und per VDV 261 übertragene Zeit zur Vorkonditionierung zur verwenden (prec_reqtime), die Frage ist nur ob diese hilfreich ist, wenn die Berechnung auf Basis der reduzierten minimale Erhaltungsladung erfolgt.

**Comment by maikwoehl-psi** [comment]
So würde ich also folgende Ergänzung vorschlagen:

```xml
"AutomaticPreconditioning": {
	"description": "This type imposes properties regarding automatic preconditioning.",
	"type": "object",
	"properties": {
		"preconditioningRequest": {
			"$ref": "#/definitions/PreconditioningRequest"
		},
		"ambientTemperature": {
			"type": "number",
			"additionalProperties": false
		},
		"requestedStartTime": {
			"type": "string",
			"format": "date-time",
			"additionalProperties": false
		}
		"requestedFinishTime": {
			"type": "string",
			"format": "date-time",
			"additionalProperties": false
		}
	},
	"required": [
		"preconditioningRequest"
	],
	"additionalProperties": false
},
```

**Comment by maikwoehl-psi** [comment]
- [ ] Änderung des Spezifikationsdokument noch notwendig?

**Comment by DohmenClaus** [comment]
Abbildung in Kap. 2.2.3 muss noch angepasst werden

**Comment by maikwoehl-psi** [comment]
Aus dem heutigen Termin am 01.07.2024 hat sich ergeben, dass das BMS/ITCS in der Lage sein soll für die automatische Vorkonditionierung den Zeitpunkt übermitteln kann, bei dem die Leistung zur Vorkonditionierung vom LMS zur Verfügung gestellt werden soll. 

Die Erläuterung in dem Spezifikationsdokument soll besser ausgeführt werden.
